const data = {
	status: "success",
	items: [
	{
		id: 1;
		title: "Nike Air Force 1",
		price: 401,
		image: require('./images/img01.png'),
		category: "nike",
		img1: "https://www.revistagq.com/moda/articulo/zapatillas-nike-mas-vendidas-espana-2021/img",
		img2: ".jpg?auto=format,compress&q=90&updated_at=1606321430&w=1000",
		cantidad: 1,
	},
	{
		id: 2
		title: "Nike Dunk Low Off-White Pine Green",
		price: 304,
		image: require('./images/img02.png'),
		category: "nike",
		img1: "https://www.nike.com/es/w/air-force-1-zapatillas-5sj3yzy7ok/img",
		img2: ".jpg?auto=format,compress&q=90&updated_at=1606319825&w=1000",
		cantidad: 1,
	},
	{
		id: 3,
		title: "Nike Air Force 1 Low Supreme Black",
		price: 475,
		image: require('./images/img03.png'),
		category: "nike",
		img1: "https://www.nike.com/es/w/jordan-1-zapatillas-4fokyzy7ok/img",
		img2: ".jpg?auto=format,compress&q=90&updated_at=1606319825&w=1000",
		cantidad: 1,
	},
	{
		id: 4,
		title: "Nike LD Waffle Sacai White Nylon",
		price: 399,
		image: require('./images/img04.png'),
		category: "nike",
		img1: "https://www.amazon.com/-/es/Sudadera-capucha-para-hombre-Sportswear/dp/B07DL1G3WW/img",
		img2: ".jpg?auto=format,compress&q=90&updated_at=160632533&w=1000",
		cantidad: 1,
	},
	{
		id: 5,
		title: "Nike Dunk Low SP Kentucky (2021)",
		price: 405,
		image: require('./images/img04.png'),
		category: "nike",
		img1: "https://www.samtabak.com/us/nike-sportswear-club-fleece-pullover-hoodie-grey-b.html/img",
		img2: ".jpg?auto=format,compress&q=90&updated_at=1606322330&w=1000",
		cantidad: 1,
	},
	{
		id: 6,
		title: "Nike Dunk Low Off-White University",
		price: 399,
		image: require('./images/img04.png'),
		category: "nike",
		img1: "https://www.shopingvips.xyz/products.aspx?cname=rode+nike+hoodie&cid=66/img",
		img2: ".jpg?auto=format,compress&q=90&updated_at=1606322330&w=1000",
		cantidad: 1,
	},
	{
		id: 7,
		title: "Nike Dunk Low Off-White University",
		price: 399,
		image: require('./images/img04.png'),
		category: "nike",
		img1: "https://www.nike.com/es/w/hombre-gorros-52r49znik1/img",
		img2: ".jpg?auto=format,compress&q=90&updated_at=1606322330&w=1000",
		cantidad: 1,
	},
	{
		id: 8,
		title: "Nike Dunk Low Off-White University",
		price: 399,
		image: require('./images/img04.png'),
		category: "nike",
		img1: "https://www.nike.com/es/w/gorras-66dm/img",
		img2: ".jpg?auto=format,compress&q=90&updated_at=1606322330&w=1000",
		cantidad: 1,
	},
	{
		id: 9,
		title: "Nike Dunk Low Off-White University",
		price: 399,
		image: require('./images/img04.png'),
		category: "nike",
		img1: "https://laopinion.com/guia-de-compras/variedad-de-disenos-de-sandalias-y-chanclas-nike-para-usar-en-tu-casa/img",
		img2: ".jpg?auto=format,compress&q=90&updated_at=1606322330&w=1000",
		cantidad: 1,
	},
	{
		id: 10,
		title: "Nike Dunk Low Off-White University",
		price: 399,
		image: require('./images/img04.png'),
		category: "nike",
		img1: "https://www.sneakersvip365.top/products.aspx?cname=chanclas+nike+azul+turquesa&cid=195/img",
		img2: ".jpg?auto=format,compress&q=90&updated_at=1606322330&w=1000",
		cantidad: 1,
	},
	{
		id: 11,
		title: "Nike Dunk Low Off-White University",
		price: 399,
		image: require('./images/img04.png'),
		category: "nike",
		img1: "https://www.complex.com/sneakers/most-important-nike-logos-of-all-time/img",
		img2: ".jpg?auto=format,compress&q=90&updated_at=1606322330&w=1000",
		cantidad: 1,
	}]
}